apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/midnightrocket-education/devops-e24/simple-fortune/backend:latest
        name: backend-container
        ports:
          - containerPort: 9000
        env:
        - name: REDIS_DNS
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
