name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy on'
        type: environment
        required: true

  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy on'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    env:
      KUBECONFIG: "${{ github.workspace }}/.kubeconfig"
      KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
    steps:
      - uses: actions/checkout@v4

      - name: "Create kube config"
        run: echo "$KUBECONFIG_CONTENT" | base64 -d > "$KUBECONFIG"

      - run: sh ci/deploy.sh apply
