name: "Integration test autorunner"
# This is for testing the pipeline only
# Should be deleted before merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/integration-test.yaml
    secrets: inherit
    with:
      environment: testing
