name: "Integration test"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

  workflow_call:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    env:
      KUBECONFIG: "${{ github.workspace }}/.kubeconfig"
      KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
    steps:
      - uses: actions/checkout@v4
      - name: "Create kube config"
        run: echo "$KUBECONFIG_CONTENT" | base64 -d > "$KUBECONFIG"
      - run: sh ci/deploy.sh "$KUBECONFIG"

  test:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    needs:
      - deploy
    env:
      KUBECONFIG: "${{ github.workspace }}/.kubeconfig"
      KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
      WORKSTATION_ID: ${{ vars.WORKSTATION_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: "Create kube config"
        run: echo "$KUBECONFIG_CONTENT" | base64 -d > "$KUBECONFIG"

      - name: debug
        run: |
          stat --printf="Kubeconfig size %s\n" "$KUBECONFIG"
          printf "KUBECONFIG_CONTENT length: "
          printf "%b" "$KUBECONFIG_CONTENT" | wc -c
          echo "ENV: ${{ inputs.environment }}"
          echo "WORKSTATION_ID $WORKSTATION_ID"

      - name: "Trying to curl endpoint"
        run: "./ci/integration_test/curl_endpoint.sh"
